networks:
  default: studionet

  localnet:
    url: "http://127.0.0.1:4000/api"

  studionet:
    url: "https://studio-next.genlayer.com/api"

paths:
  contracts: "contracts"

environment: .env.local
